server:
  port: 2222
  
  #client application name
  
spring:
  application:
    name: CLIENT-TWO
  # to register client with admin server (with admin server url)(used to monitor the application using actuators 
  boot:
    admin:
      client:
        url: http://localhost:9090/
 #for api's exposing all the actuator endpoints       
management:
  endpoints:
    web:
      exposure:
        include: '*'
                