management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:9090}/eureka/
server:
  port: 1111
spring:
  application:
    name: STOCK-PRICE-API
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:mem:test
    username: sa

    
    #ORM source properties
      
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
 