server:
  port: 3333
    
spring:
  application:
    name: SB-GATEWAY-API  
    
    
    #define port no manually wen v are using port no other than 8761
eureka:
  client:
    service-url:
      defaultZone : ${DISCOVERY-URL:http://localhost:9090}/eureka/        
zuul:
  prefix: /ms
  routes:
    greet :
      path : /api1/**
      serviceId : GREET-API
    welcome :
      path : /api2/**
      serviceId : WELCOME-API 